import * as Web from "src/web/Mod";

export type TextProps = {
    textAlign?: Web.CssProps["textAlign"];
    textAlignLast?: Web.CssProps["textAlignLast"];
    textAnchor?: Web.CssProps["textAnchor"];
    textCombineUpright?: Web.CssProps["textCombineUpright"];
    textDecoration?: Web.CssProps["textDecoration"];
    textDecorationColor?: Web.CssProps["textDecorationColor"];
    textDecorationLine?: Web.CssProps["textDecorationLine"];
    textDecorationSkip?: Web.CssProps["textDecorationSkip"];
    textDecorationSkipInk?: Web.CssProps["textDecorationSkipInk"];
    textDecorationStyle?: Web.CssProps["textDecorationStyle"];
    textDecorationThickness?: Web.CssProps["textDecorationThickness"];
    textEmphasis?: Web.CssProps["textEmphasis"];
    textEmphasisColor?: Web.CssProps["textEmphasisColor"];
    textEmphasisPosition?: Web.CssProps["textEmphasisPosition"];
    textEmphasisStyle?: Web.CssProps["textEmphasisStyle"];
    textIndent?: Web.CssProps["textIndent"];
    textJustify?: Web.CssProps["textJustify"];
    textOrientation?: Web.CssProps["textOrientation"];
    textOverflow?: Web.CssProps["textOverflow"];
    textRendering?: Web.CssProps["textRendering"];
    textShadow?: Web.CssProps["textShadow"];
    textSizeAdjust?: Web.CssProps["textSizeAdjust"];
    textTransform?: Web.CssProps["textTransform"];
    textUnderlineOffset?: Web.CssProps["textUnderlineOffset"];
    textUnderlinePosition?: Web.CssProps["textUnderlinePosition"];
    textWrap?: Web.CssProps["textWrap"];
    verticalAlign?: Web.CssProps["verticalAlign"];
};